apiVersion: v1
kind: Service
metadata:
  name: apl-spring
  labels:
    app: apl-spring
spec:
  type: ClusterIP
  selector:
    app: apl-spring
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http

