apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green
  namespace: argocd
spec:
  # 
  project: app-dev
  source:
    repoURL: https://github.com/rinakia/argocd-app.git
    targetRevision: main
    path: apps/blue-green
  destination:
    server: https://kubernetes.default.svc
    namespace: apl-tada
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
