apiVersion: v1
kind: Service
metadata:
  name: bluegreen-demo-preview
  labels:
    app: bluegreen-demo
spec:
  type: ClusterIP
  # NodePort to Ingress
  #type: NodePort
  selector:
    app: bluegreen-demo
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 32080
